apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: pgsql
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 3
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgresql-backup
              image: ghcr.io/shanginn/k8s-pgsql-backup:latest
              command: ["run-pgsql-backup"]
              imagePullPolicy: "IfNotPresent"
              env:
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: creds
                      key: postgres-password
                - name: PGHOST
                  value: pgsql-postgresql
                - name: PGPORT
                  value: "5432"
          restartPolicy: OnFailure