apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: test-container
          image: ghcr.io/shanginn/k8s-pgsql-backup:latest
          command: ["sleep", "infinity"]  # Just to keep the container running