# tem disable
{{- if false }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pgsql-backup.fullname" . }}
  labels:
    {{- include "pgsql-backup.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 3
  schedule: "0 7,19 * * *" # every 12 hours
  jobTemplate:
    metadata:
      labels:
        {{- include "pgsql-backup.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          serviceAccountName: {{ include "pgsql-backup.serviceAccountName" . }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
                {{- toYaml . | nindent 8 }}
              {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["run-pgsql-backup"]
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: creds
                      key: postgres-password
              envFrom:
                - configMapRef:
                    name: {{ include "pgsql-backup.fullname" . }}-env
                - secretRef:
                    name: {{ include "pgsql-backup.fullname" . }}-secret
          restartPolicy: OnFailure
{{end}}