apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "pgsql-backup.fullname" . }}-secret"
  labels:
    environment: "{{ .Chart.Name }}"
    {{- include "pgsql-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
