databases:
  - name: generach
    schedule: "0 7,19 * * *" # every 12 hours
  - name: sistent
    schedule: "0 0 * * *" # every 24 hours

enableTestPod: false

imagePullSecrets:
  - name: dockerconfigjson-github-com

image:
  repository: ghcr.io/shanginn/k8s-pgsql-backup
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  name: "pgsql-backup"

env:
  PGUSER: postgres
  PGHOST: pgsql-postgresql
  PGPORT: "5432"

envSecrets:
  CLOUDFLARE_ACCOUNT_ID: ""
  CLOUDFLARE_API_TOKEN: ""
  CLOUDFLARE_ACCESS_KEY_ID: ""
  CLOUDFLARE_SECRET_ACCESS_KEY: ""
