name: Build and Deploy

on:
  push:
    branches:
      - mother

jobs:
  build:
    permissions: write-all
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print tolower($2)}')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
#
#  deploy:
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    steps:
#      - uses: actions/checkout@v4
#      - uses: oven-sh/setup-bun@v1
#      - run: bun install
#      - run: bun run build
#      - name: Build & Deploy Worker
#        uses: cloudflare/wrangler-action@v3
#        with:
#          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#          command: pages deploy dist --project-name=removebg